kind: pipeline
type: docker
name: publish

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: maxvasin/npm_proxy
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
